routes/web.php
<?php
use App\Artigo;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', function (Request $req) {
  // dd($req);  // tipo o vardump do php
  if(isset($req->busca) && $req->busca != ""){
    $busca = $req->busca;
    $lista = Artigo::listaArtigosSite(3,$busca);

    //busca
  }else{
    $lista = Artigo::listaArtigosSite(3);
    $busca = "";
  }
    return view('site',compact('lista','busca'));
})->name('site');


Route::get('/artigo/{id}/{titulo?}', function ($id) {
    $artigo = Artigo::find($id);
    if($artigo){
      return view('artigo',compact('artigo'));
    }
    return redirect()->route('site');

})->name('artigo');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@index')->name('admin')->middleware('can:autor');

Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group(function(){
  Route::resource('artigos', 'ArtigosController')->middleware('can:autor');
  Route::resource('usuarios', 'UsuariosController')->middleware('can:eAdmin');
  Route::resource('autores', 'AutoresController')->middleware('can:eAdmin');
  Route::resource('adm', 'AdminController')->middleware('can:eAdmin');
});


//Route::resource('photos', 'PhotoController');

resources/views/admin.blade.php
@extends('layouts.app')

@section('content')
  <pagina tamanho="10">
    <painel titulo="Dashboard">
      <migalhas v-bind:lista="{{$listaMigalhas}}"></migalhas>

      <div class="row">
        @can('autor')
          <div class="col-md-4">
            <caixa qtd="{{$totalArtigos}}" titulo="Artigos" url="{{route('artigos.index')}}" cor="orange" icone="ion ion-pie-graph"></caixa>
          </div>
        @endcan

        @can('eAdmin')
          
          <div class="col-md-4">
            <caixa qtd="{{$totalUsuarios}}" titulo="Usuários" url="{{route('usuarios.index')}}" cor="blue" icone="ion ion-person-stalker"></caixa>
          </div>
          <div class="col-md-4">
            <caixa qtd="{{$totalAutores}}" titulo="Autores" url="{{route('autores.index')}}" cor="red" icone="ion ion-person"></caixa>
          </div>
          <div class="col-md-4">
            <caixa qtd="{{$totalAdmin}}" titulo="Admin" url="{{route('adm.index')}}" cor="green" icone="ion ion-person"></caixa>
          </div>
        @endcan

      </div>
    </painel>

  </pagina>
@endsection
{{-- <!--{{$totalArtigos}}{{$totalUsuarios}}{{$totalAutores}}--> --}}

resources/views/artigo.blade.php
@extends('layouts.app')

@section('content')
  <pagina tamanho="12">
    <painel>

      <h2 align="center">{{$artigo->titulo}}</h2>
      <h4 align="center">{{$artigo->descricao}}</h4>
      <p>
        {{-- !!aqui tem um html --}}
        {!!$artigo->conteudo!!}

      </p>
      <p align="center">
        {{-- metodo do PHP - strtotime --}}
        <small>Por: {{$artigo->user->name}} - {{date('d/m/Y',strtotime($artigo->data))}}</small>
      </p>
    </painel>

  </pagina>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
  <pagina tamanho="10">
    <painel titulo="Dashboard">
      <migalhas v-bind:lista="{{$listaMigalhas}}"></migalhas>

      <div class="row">
        <div class="col-md-4">
          <caixa qtd="{{$totalArtigos}}" titulo="Artigos" url="{{route('artigos.index')}}" cor="orange" icone="ion ion-pie-graph"></caixa>
        </div>
        <div class="col-md-4">
          <caixa qtd="{{$totalUsuarios}}" titulo="Usuários" url="{{route('usuarios.index')}}" cor="blue" icone="ion ion-person-stalker"></caixa>
        </div>
        <div class="col-md-4">
          <caixa qtd="{{$totalAutores}}" titulo="Autores" url="{{route('autores.index')}}" cor="red" icone="ion ion-person"></caixa>
        </div>
      </div>
    </painel>

  </pagina>
@endsection
{{-- <!--{{$totalArtigos}}{{$totalUsuarios}}{{$totalAutores}}--> --}}

resources/views/site.blade.php
@extends('layouts.app')

@section('content')
  <pagina tamanho="10">
    <painel titulo="Artigos">

      <p>
        <form class="form-inline text-center" action="{{route('site')}}" method="get">
          <input type="search" class="form-control" name="busca" placeholder="Buscar" value="{{isset($busca) ? $busca : ""}}">
          <button class="btn btn-info">Buscar</button>
        </form>

      </p>

      <div class="row">
        @foreach ($lista as $key => $value)
          <artigocard
          titulo="{{str_limit($value->titulo,25,"...")}}"
          descricao="{{str_limit($value->descricao,30,"...")}}"
          link="{{route('artigo',[$value->id,str_slug($value->titulo)])}}"
          imagem="https://coletiva.net/files/e4da3b7fbbce2345d7772b0674a318d5/midia_foto/20170713/118815-maior_artigo_jul17.jpg"
          data="{{$value->data}}"
          autor="{{$value->autor}}"
          sm="6"
          md="4">
          </artigocard>
        @endforeach
        {{-- <artigocard
        titulo="Titulo teste"
        descricao="Laravel e vue js"
        link="#"
        imagem="https://coletiva.net/files/e4da3b7fbbce2345d7772b0674a318d5/midia_foto/20170713/118815-maior_artigo_jul17.jpg"
        data="22/04/2018"
        autor="Renato"
        sm="6"
        md="4"

        >
        </artigocard> --}}

      </div>
      <div align="center">
        {{$lista}}
      </div>

    </painel>

  </pagina>
@endsection

resources/views/teste.blade.php
@extends('layouts.app')

@section('content')
  <pagina tamanho="10">
    <painel titulo="Artigos">
      <div class="row">
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <img src="https://coletiva.net/files/e4da3b7fbbce2345d7772b0674a318d5/midia_foto/20170713/118815-maior_artigo_jul17.jpg" alt="...">
            <div class="caption">
              <h3>Ilustraçao</h3>
              <p>Imagem meramente ilustrativa</p>
              <p><a href="#" class="btn btn-primary" role="button">Ler mais</a></p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <img src="https://coletiva.net/files/e4da3b7fbbce2345d7772b0674a318d5/midia_foto/20170713/118815-maior_artigo_jul17.jpg" alt="...">
            <div class="caption">
              <h3>Ilustraçao</h3>
              <p>Imagem meramente ilustrativa</p>
              <p><a href="#" class="btn btn-primary" role="button">Ler mais</a></p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <img src="https://coletiva.net/files/e4da3b7fbbce2345d7772b0674a318d5/midia_foto/20170713/118815-maior_artigo_jul17.jpg" alt="...">
            <div class="caption">
              <h3>Ilustraçao</h3>
              <p>Imagem meramente ilustrativa</p>
              <p><a href="#" class="btn btn-primary" role="button">Ler mais</a></p>
            </div>
          </div>
        </div>
      </div>

    </painel>

  </pagina>
@endsection